version: '3.3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: stock_market
    ports:
      - "3306:3306"